import { PageLayout } from '@/components/PageLayout';

export default function Disclaimer() {
  return (
    <PageLayout title="Disclaimer">
      <p><em>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</em></p>

      <h2 className="text-xl font-semibold text-foreground mt-6">General Disclaimer</h2>
      <p>
        The information provided on CryptoPulse is for general informational purposes only. All information on the site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, or completeness of any information on the site.
      </p>

      <h2 className="text-xl font-semibold text-foreground mt-6">Investment Disclaimer</h2>
      <p>
        CryptoPulse does not provide financial, investment, or trading advice. Cryptocurrency markets are highly volatile and carry significant risk. Past performance is not indicative of future results. Always conduct your own research and consult with a qualified financial advisor before making any investment decisions.
      </p>

      <h2 className="text-xl font-semibold text-foreground mt-6">AI-Generated Content</h2>
      <p>
        Our website features an AI-powered Q&A tool that provides information about cryptocurrencies. Responses generated by AI are for informational purposes only and should not be relied upon as financial advice. AI responses may contain inaccuracies or outdated information.
      </p>

      <h2 className="text-xl font-semibold text-foreground mt-6">External Links</h2>
      <p>
        Our website may contain links to third-party websites. We have no control over the content, privacy policies, or practices of any third-party sites and assume no responsibility for them.
      </p>

      <h2 className="text-xl font-semibold text-foreground mt-6">Contact</h2>
      <p>
        If you have questions about this Disclaimer, please contact us at support@cryptopulse.com.
      </p>
    </PageLayout>
  );
}
